swagger: "2.0"
info:
  version: "0.0.1"
  title: State of California POC
host: localhost:10010
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
x-a127-config: {}
x-a127-services: {}
paths:
  /persons/{id}/events:
    x-swagger-router-controller: persons
    x-a127-apply: {}
    get:
      description: Returns details about a person
      operationId: persons
      parameters:
      - name: id
        in: path
        description: The identification number of a person
        required: true
        type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PersonsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /events/{id}:
    x-swagger-router-controller: events
    x-a127-apply: {}
    get:
      description: Returns details about an event
      operationId: events
      parameters:
      - name: id
        in: path
        description: The identification number of an event
        required: true
        type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/eventItem"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  eventItem:
    properties:
    #  eventId:
    #    type: integer
      date:
        type: string
        format: date
      type:
        type: string
      status:
        type: string
      eventDetails:
        type: string
      personsInvolved:
        type: array
        items:
          type: integer
      roles:
        type: array
        items:
          $ref: "#/definitions/rolesItem"
  rolesItem:
    properties:
      personId:
        type: integer
    #  name:
    #    type: string
      role:
        type: string
    #  relationship:
    #    type: string
  PersonsResponse:
    properties:
      id:
        type: integer
    #  filter:
    #    type: string
      firstName:
        type: string
      lastName:
        type: string
      DOB:
        type: string
        format: date
      SSN:
        type: string
      gender:
        type: string
      age:
        type: integer
      relationships:
        type: array
        items:
          type: string
    #  events:
    #    type: array
    #    items:
    #      $ref: "#/definitions/eventItem"
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string